# Generated by Django 3.0.3 on 2020-02-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_production', models.CharField(max_length=127)),
                ('url_test', models.CharField(max_length=127)),
                ('release', models.CharField(max_length=127)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
