# Generated by Django 3.0.3 on 2020-02-19 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
