# Generated by Django 3.0.3 on 2020-02-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager_testing', '0002_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_production', models.CharField(max_length=127, null=True)),
                ('url_test', models.CharField(max_length=127, null=True)),
                ('proxy_test', models.CharField(max_length=127, null=True)),
                ('version_test', models.CharField(max_length=127, null=True)),
                ('render', models.CharField(max_length=127, null=True)),
                ('release', models.CharField(max_length=127, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
