# Generated by Django 3.0.3 on 2020-02-19 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0003_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=3)),
                ('carrier_id', models.PositiveIntegerField()),
                ('carrier_name', models.CharField(max_length=127)),
                ('service_id', models.PositiveIntegerField()),
                ('service_name', models.CharField(max_length=127)),
                ('result', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_testing.Test')),
            ],
        ),
    ]
