# Generated by Django 3.0.3 on 2020-02-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0004_testplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='logistic_type',
            field=models.CharField(blank=True, choices=[('DS', 'Drop off'), ('XD-DS', 'Cross docking y Drop off'), ('XD', 'Cross docking'), ('FF', 'Fulfillment'), ('FLEX', 'Flex')], max_length=10, null=True),
        ),
    ]
