# Generated by Django 3.0.3 on 2020-02-19 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0005_testplan_logistic_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=127)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='carrier_id',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='carrier_name',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='service_name',
        ),
        migrations.AddField(
            model_name='testplan',
            name='shipment_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='site_id',
            field=models.CharField(choices=[('MLB', 'MLB'), ('MLA', 'MLA'), ('MLC', 'MLC'), ('MLU', 'MLU'), ('MCO', 'MCO'), ('MLM', 'MLM')], max_length=3),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=127)),
                ('enabled', models.BooleanField(default=False)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_testing.Carrier')),
            ],
        ),
        migrations.AddField(
            model_name='testplan',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_testing.Service'),
        ),
    ]
