# Generated by Django 3.0.3 on 2020-02-19 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0006_auto_20200219_0134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestPlan',
        ),
    ]
