# Generated by Django 3.0.3 on 2020-02-19 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0007_delete_testplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(choices=[('MLB', 'MLB'), ('MLA', 'MLA'), ('MLC', 'MLC'), ('MLU', 'MLU'), ('MCO', 'MCO'), ('MLM', 'MLM')], max_length=3)),
                ('logistic_type', models.CharField(blank=True, choices=[('DS', 'Drop off'), ('XD-DS', 'Cross docking y Drop off'), ('XD', 'Cross docking'), ('FF', 'Fulfillment'), ('FLEX', 'Flex')], max_length=10, null=True)),
                ('shipment_id', models.BigIntegerField(null=True)),
                ('result', models.BooleanField(default=False)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_testing.Service')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_testing.Test')),
            ],
        ),
    ]
