# Generated by Django 3.0.3 on 2020-02-19 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0008_testplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='code',
        ),
        migrations.RemoveField(
            model_name='service',
            name='code',
        ),
    ]
