# Generated by Django 3.0.3 on 2020-02-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0010_auto_20200219_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='site',
            field=models.CharField(choices=[('MLB', 'MLB'), ('MLA', 'MLA'), ('MLC', 'MLC'), ('MLU', 'MLU'), ('MCO', 'MCO'), ('MLM', 'MLM')], default='', max_length=3),
            preserve_default=False,
        ),
    ]
