# Generated by Django 3.0.3 on 2020-02-19 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0011_carrier_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testplan',
            name='site_id',
        ),
    ]
