# Generated by Django 3.0.3 on 2020-02-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0012_remove_testplan_site_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='shipment_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
