# Generated by Django 3.0.3 on 2020-02-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0013_auto_20200219_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='logistic_type',
            field=models.CharField(blank=True, choices=[('drop_off', 'Drop off'), ('xd_drop_off', 'Cross docking y Drop off'), ('cross_docking', 'Cross docking'), ('fulfillment', 'Fulfillment'), ('self_service', 'Flex')], max_length=20, null=True),
        ),
    ]
