# Generated by Django 3.0.3 on 2020-02-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0014_auto_20200219_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testplan',
            name='result',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='test',
        ),
    ]
