# Generated by Django 3.0.3 on 2020-02-19 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0015_auto_20200219_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testplan',
            name='shipment_id',
        ),
    ]
