# Generated by Django 3.0.3 on 2020-02-19 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0021_test_execute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='execute',
        ),
    ]
