# Generated by Django 3.0.3 on 2020-02-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0023_test_execute'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplanresult',
            name='image_diff',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
