# Generated by Django 3.0.3 on 2020-02-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0025_auto_20200219_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplanresult',
            name='image_diff',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
