# Generated by Django 3.0.3 on 2020-02-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0026_auto_20200219_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='execute',
            new_name='is_running',
        ),
        migrations.AddField(
            model_name='test',
            name='running_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='running_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
