# Generated by Django 3.0.3 on 2020-02-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0027_auto_20200222_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='dpmm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testplan',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testplan',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='response_type',
            field=models.CharField(blank=True, choices=[('PDF', 'PDF'), ('ZPL2', 'ZPL'), ('JSON', 'JSON')], max_length=4, null=True),
        ),
    ]
