# Generated by Django 3.0.3 on 2020-02-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0028_auto_20200222_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testplanresult',
            old_name='image_diff',
            new_name='image_production',
        ),
        migrations.AddField(
            model_name='test',
            name='fail_test',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='success_test',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='total_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testplanresult',
            name='image_test',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
