# Generated by Django 3.0.3 on 2020-02-24 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0029_auto_20200224_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=0)),
                ('result', models.TextField(blank=True, null=True)),
                ('test_plan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_testing.TestPlanResult')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('image_a', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_b', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('test_plan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_testing.TestPlanResult')),
            ],
        ),
    ]
