# Generated by Django 3.0.3 on 2020-02-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0030_imagesresult_stepresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepresult',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
