# Generated by Django 3.0.3 on 2020-02-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0031_stepresult_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesresult',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
