# Generated by Django 3.0.3 on 2020-02-24 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0032_imagesresult_success'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagesResult',
            new_name='ImageResult',
        ),
    ]
