# Generated by Django 3.0.3 on 2020-02-24 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0034_auto_20200224_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('url', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='QueryParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=127)),
                ('value', models.CharField(max_length=127)),
                ('access_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_testing.AccessPoint')),
            ],
        ),
    ]
