# Generated by Django 3.0.3 on 2020-02-24 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0035_accesspoint_queryparam'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='access_point_a',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='access_point_a', to='manager_testing.AccessPoint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='access_point_b',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='access_point_b', to='manager_testing.AccessPoint'),
            preserve_default=False,
        ),
    ]
