# Generated by Django 3.0.3 on 2020-02-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0036_auto_20200224_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='proxy_test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='release',
        ),
        migrations.RemoveField(
            model_name='test',
            name='render',
        ),
        migrations.RemoveField(
            model_name='test',
            name='url_production',
        ),
        migrations.RemoveField(
            model_name='test',
            name='url_test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='version_test',
        ),
    ]
