# Generated by Django 3.0.3 on 2020-02-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0037_auto_20200224_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='release',
            field=models.CharField(default='', max_length=127),
        ),
    ]
