# Generated by Django 3.0.3 on 2020-03-18 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0039_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_testing.Facility'),
        ),
    ]
