# Generated by Django 3.0.3 on 2020-04-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0040_testplan_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='caller_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='response_type',
            field=models.CharField(blank=True, choices=[('PDF', 'PDF'), ('ZPL2', 'ZPL'), ('JSON', 'JSON'), ('NONE', 'NONE')], max_length=4, null=True),
        ),
    ]
