# Generated by Django 3.0.3 on 2020-04-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_testing', '0041_auto_20200402_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='use_preferences',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='response_type',
            field=models.CharField(blank=True, choices=[('PDF', 'PDF'), ('ZPL2', 'ZPL'), ('JSON', 'JSON')], max_length=4, null=True),
        ),
    ]
